version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./python-fastapi-poc:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://demo_user:Password.123@localhost:15432/demo
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 15432
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=Password.123
      - POSTGRES_DB=demo
